config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :workspaces, only: %i[index show create update destroy] do
    resources :checklists, only: %i[create]
  end

  resources :checklists, only: %i[show edit update destroy] do
    resources :sections, only: %i[create]
  end

  resources :sections, only: %i[update destroy] do
    resources :steps, only: %i[create]
  end

  resources :steps, only: %i[update destroy]

  namespace :share do
    resources :checklists, only: %i[show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :workspace
  has_many :sections, dependent: :destroy

  validates :name, presence: true
  validates :workspace, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :checklist
  has_many :steps, dependent: :destroy
  acts_as_list scope: :checklist

  validates :title, presence: true
  validates :checklist, presence: true
  validates :position, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :section
  acts_as_list scope: :section

  validates :title, presence: true
  validates :position, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :workspaces, foreign_key: :owner_id, dependent: :destroy
  has_many :checklists, through: :workspaces

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id, required: true
  has_many :checklists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^share)/
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :set_checklist, only: %i[show edit update destroy]
  before_action :show_sidebar, only: %i[show]

  def show
    authorize @checklist
  end

  def create
    @checklist = Checklist.new
    @checklist.workspace = Workspace.find(params[:workspace_id])
    authorize @checklist

    if @checklist.save
      redirect_to checklist_path(@checklist)
    else
      render 'workspaces/show', status: :unprocessable_entity
    end
  end

  def edit
    authorize @checklist
  end

  def update
    authorize @checklist

    if @checklist.update(checklist_params)
      render :edit, status: :ok
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @checklist

    @checklist.destroy
    redirect_to workspace_path(@checklist.workspace)
  end

  private

  def set_checklist
    @checklist = Checklist.find(params[:id])
  end

  def checklist_params
    params.require(:checklist).permit(:name, :description, :start_date, :estimated_end_date)
  end

  def show_sidebar
    @show_sidebar = true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :show_navbar

  def home
  end

  private

  def show_navbar
    @show_navbar = true
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[update destroy]

  def create
    @checklist = Checklist.find(params[:checklist_id])
    @section = @checklist.sections.new(section_params)
    @section.position = @checklist.sections.count + 1
    authorize @section

    respond_to do |format|
      format.json if @section.save
    end
  end

  def update
    authorize @section

    @section.update(section_params)
  end

  def destroy
    authorize @section

    @section.destroy
  end

  private

  def section_params
    params.require(:section).permit(:title, :position)
  end

  def set_section
    @section = Section.find(params[:id])
  end
end

app/controllers/share/checklists_controller.rb
class Share::ChecklistsController < ApplicationController
  def show
    @checklist = Checklist.find(params[:id])
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: %i[update destroy]

  def create
    @section = Section.find(params[:section_id])
    @step = @section.steps.new(step_params)
    @step.position = @section.steps.count + 1
    authorize @step

    respond_to do |format|
      format.json if @step.save
    end
  end

  def update
    authorize @step

    @step.update(step_params)
  end

  def destroy
    authorize @step

    @step.destroy
  end

  private

  def step_params
    params.require(:step).permit(:title, :position)
  end

  def set_step
    @step = Step.find(params[:id])
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :set_workspace, only: %i[show update destroy]
  before_action :show_sidebar, only: %i[index show]

  def index
    @workspaces = policy_scope(Workspace)
  end

  def show
    authorize @workspace
  end

  def create
    @workspace = Workspace.new
    @workspace.owner = current_user
    authorize @workspace

    if @workspace.save
      redirect_to workspace_path(@workspace)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def update
    authorize @workspace

    @workspace.update(workspace_params)
  end

  def destroy
    authorize @workspace

    @workspace.destroy
    redirect_to workspaces_path
  end

  private

  def set_workspace
    @workspace = Workspace.find(params[:id])
  end

  def workspace_params
    params.require(:workspace).permit(:name)
  end

  def show_sidebar
    @show_sidebar = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checklists/_checklist.html.erb
<tr class="ck__row">
  <td class="ck__name"><%= link_to checklist.name, checklist_path(checklist) %></td>
  <td><div class="ck__status ck__status--published">Published</div></td>
  <td class="ck__creator">Toto</td>
  <td class="ck__completion">5 completed</td>
  <td><i class="bx bx-dots-horizontal-rounded"></i></td>
</tr>

app/views/checklists/_edit_header.html.erb
  <div>
    <%= link_to checklist_path(checklist), class: 'button--secondary' do %>
    <i class="bx bx-left-arrow-alt"></i>
    Leave editor
    <% end %>
  </div>
  <div class="actions__list">
    <div class="actions_item">New section</div>
    <div class="actions_item">New task</div>
    <div class="actions_item">Preview</div>
    <div class="actions_item">Other action</div>
  </div>
  <div>
    <%= link_to "Publish", "#", class: "button--primary" %>
  </div>

app/views/checklists/edit.html.erb
<header class="edit__header">
  <%= render "checklists/edit_header", checklist: @checklist %>
</header>
<main class="edit__main">
  <div class="checklist">
    <div class="checklist__header">
      <div class="checklist__name"
           contenteditable="true"
           data-controller="editing"
           data-editing-target="item"
           data-action="focusout->editing#save"
           data-id="<%= @checklist.id %>"
           data-route="checklists"
           data-type="name">
        <%= @checklist.name %>
      </div>
      <div class="checklist__dates">
        <div class="checklist__date">
          <i class="bx bx-play-circle"></i>
          <div>
            Start on : <%= @checklist.start_date.strftime('%d/%m/%Y') if @checklist.start_date %>
          </div>
        </div>
        <div class="checklist__date">
          <i class="bx bx-stop-circle"></i>
          <div>
            Target on : <%= @checklist.estimated_end_date.strftime('%d/%m/%Y') if @checklist.estimated_end_date %>
          </div>
        </div>
      </div>
      <div class="checklist__description"
           contenteditable="true"
           data-controller="editing"
           data-editing-target="item"
           data-action="focusout->editing#save"
           data-id="<%= @checklist.id %>"
           data-route="checklists"
           data-type="description">
        <%= @checklist.description %>
      </div>
    </div>
    <div class="checklist__content">
      <div class="checklist__sections" data-controller="drag" data-route="/sections">
        <% @checklist.sections.order(position: :asc).each do |section| %>
          <%= render "sections/section", section: section %>
        <% end %>
        <div class="add-button"
            data-controller="editing"
            data-editing-target="button"
            data-action="click->editing#add"
            data-parent-id="<%= @checklist.id %>"
            data-new-item="section">
          <i class='bx bx-plus'></i>
          <div>Add a new section</div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/checklists/show.html.erb
<main class="app__container">
  <header class="app__header">
    <div class="app__header--left">
      <h1><%= @checklist.name %></h1>
      <div class="header__options">
        <div data-controller="dropdown" class="relative">
          <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class="dropdown__button"><i class='bx bx-cog'></i></button>
          <div data-dropdown-target="menu" class="hidden dropdown__list">
            <%= render "shared/modal", route: "/checklists/#{@checklist.id}" %>
            <%= link_to 'Delete', checklist_path(@checklist), data: {turbo_method: :delete, action: "dropdown#toggle" } %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to edit_checklist_path(@checklist), class: "button--primary" do %>
      <i class="bx bx-edit"></i>
      Edit
    <% end %>
  </header>
  <div class="app__content">
    <div class="tabs">
      <%= link_to "Completion", "#", class: "tabs__link tabs__link--active" %>
      <%= link_to "Share", "#", class: "tabs__link" %>
      <%= link_to "Settings", "#", class: "tabs__link" %>
      <%= link_to "Integrations", "#", class: "tabs__link" %>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steeepz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-wrapper">
      <%= render "shared/sidebar", workspaces: policy_scope(Workspace) if @show_sidebar %>
      <%= render "shared/navbar" if @show_navbar %>
      <%= yield %>
      <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<%= link_to 'Go to my workspaces', workspaces_path %>

app/views/sections/_section.html.erb
<div class="checklist__section" data-controller="editing" data-id="<%= section.id %>">
  <div class="checklist__section-header">
    <div class="checklist__section-commands">
      <div class="checklist__section-command"
          data-editing-target="button"
          data-action="click->editing#delete"
          data-id="<%= section.id %>"
          data-route="sections">
        <i class='bx bx-trash'></i>
      </div>
      <div class="checklist__section-command"><i class='bx bx-move-vertical'></i></div>
    </div>
    <div class="checklist__section-header__title"
        contenteditable="true"
        data-editing-target="item"
        data-action="focusout->editing#save"
        data-id="<%= section.id %>"
        data-route="sections"
        data-type="title">
      <%= section.title %>
    </div>
    <div class="checklist__section-header__count">
      0 / <%= section.steps.count %> steps
    </div>
  </div>
  <div class="checklist__steps" data-controller="drag" data-route="/steps">
    <% section.steps.order(position: :asc).each do |step| %>
      <%= render "steps/step", step: step %>
    <% end %>
    <div class="add-button"
        data-controller="editing"
        data-editing-target="button"
        data-action="click->editing#add"
        data-parent-id="<%= section.id %>"
        data-new-item="step">
      <i class='bx bx-plus'></i>
      <div>Add a new step</div>
    </div>
  </div>
</div>

app/views/share/checklists/show.html.erb
<main class="share__container">
  <div class="checklist">

    <div class="checklist__header">
      <div class="checklist__name">
        <%= @checklist.name %>
      </div>
      <div class="checklist__dates">
        <div class="checklist__date">
          <i class="bx bx-play-circle"></i>
          <div>
            Start on : <%= @checklist.start_date.strftime('%d/%m/%Y') if @checklist.start_date %>
          </div>
        </div>
        <div class="checklist__date">
          <i class="bx bx-stop-circle"></i>
          <div>
            Target on : <%= @checklist.estimated_end_date.strftime('%d/%m/%Y') if @checklist.estimated_end_date %>
          </div>
        </div>
      </div>
      <div class="checklist__description">
        <%= @checklist.description %>
      </div>
    </div>

    <div class="checklist__content">
      <div class="checklist__sections">
        <% @checklist.sections.order(position: :asc).each do |section| %>
          <div class="checklist__section" data-controller="checked-counter">
            <div class="checklist__section-header">
              <div class="checklist__section-header__title">
                <%= section.title %>
              </div>
              <div class="checklist__section-header__count">
                <span data-checked-counter-target="total">0</span> / <%= section.steps.count %> steps
              </div>
            </div>

            <div class="checklist__steps">
              <% section.steps.order(position: :asc).each do |step| %>
                <div class="checklist__step">
                  <div class="step-checkbox">
                    <label for="step-<%= step.id %>" class="item" data-action="click->checked-counter#update">
                      <input type="checkbox" id="step-<%= step.id %>" data-checked-counter-target="input">
                      <label for="step-<%= step.id %>" class="cbx">
                        <svg width="14px" height="12px" viewBox="0 0 14 12">
                          <polyline points="1 7.6 5 11 13 1"></polyline>
                        </svg>
                      </label>
                      <label for="step-<%= step.id %>" class="cbx-lbl"><%= step.title %></label>
                    </label>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div data-controller="modal" data-route="<%= local_assigns[:route] %>">
  <a href="#" data-action="modal#open">Rename</a>

  <dialog data-modal-target="modal" class="modal" data-action="click->modal#clickOutside">
    <div class="modal__title">Rename</div>
    <form class="modal__form">
      <input type="text" placeholder="New name" data-modal-target="input">
      <div class="modal__buttons">
        <button type="button" data-action="modal#close" class="button--secondary">Close</button>
        <button type="button" class="button--primary" data-action="modal#save">Save</button>
      </div>
    </form>
  </dialog>
</div>

app/views/shared/_navbar.html.erb
<div>Navbar</div>
<div>
  <% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
  <% else %>
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<aside class="sidebar__container">
  <div class="sidebar__user">
    <img src="https://avatars.githubusercontent.com/u/107474450?v=4" alt="User avatar" class="avatar">
    <div class="sidebar__user__name"><%= current_user.full_name %></div>
  </div>
  <div class="sidebar__block">
    <div class="sidebar__block__title">Workspaces</div>
      <% workspaces.each do |workspace| %>
        <%= link_to workspace_path(workspace), class: "sidebar__block__list-item" do %>
          <i class='bx bx-caret-right-circle sidebar__icon'></i>
          <div><%= workspace.name %></div>
        <% end %>
      <% end %>
  </div>
  <div class="sidebar__block">
    <div class="sidebar__block__title">Resources</div>
      <%= link_to "#", class: "sidebar__block__list-item" do %>
        <i class='bx bx-collection sidebar__icon'></i>
        <div>Templates</div>
      <% end %>
      <%= link_to "#", class: "sidebar__block__list-item" do %>
        <i class='bx bx-help-circle sidebar__icon' ></i>
        <div>Help Center</div>
      <% end %>
      <%= link_to "#", class: "sidebar__block__list-item" do %>
        <i class='bx bx-message-rounded sidebar__icon' ></i>
        <div>Support</div>
      <% end %>
  </div>
  <div class="sidebar__block">
    <div class="sidebar__block__title">Product</div>
      <%= link_to "#", class: "sidebar__block__list-item" do %>
        <i class='bx bx-gift sidebar__icon' ></i>
        <div>What's new</div>
      <% end %>
      <%= link_to "#", class: "sidebar__block__list-item" do %>
        <i class='bx bx-map-alt sidebar__icon' ></i>
        <div>Roadmap</div>
      <% end %>
      <%= link_to "#", class: "sidebar__block__list-item" do %>
        <i class='bx bx-layer-plus sidebar__icon' ></i>
        <div>Request features</div>
      <% end %>
  </div>
</aside>

app/views/steps/_step.html.erb
<div class="checklist__step" data-controller="editing" data-id="<%= step.id %>">
  <div class="checklist__step-commands">
    <div class="checklist__step-command"
        data-editing-target="button"
        data-action="click->editing#delete"
        data-id="<%= step.id %>"
        data-route="steps">
      <i class='bx bx-trash'></i>
    </div>
    <div class="checklist__step-command"><i class='bx bx-move-vertical'></i></div>
  </div>
  <div class="checklist__step-main">
    <div class="checklist__step-main__icon"></div>
    <div class="checklist__step-main__title"
        contenteditable="true"
        data-editing-target="item"
        data-action="focusout->editing#save"
        data-id="<%= step.id %>"
        data-route="steps"
        data-type="title">
      <%= step.title %>
    </div>
  </div>
</div>

app/views/workspaces/_workspace_index.html.erb
<% workspaces.each do |workspace| %>
  <%= link_to workspace_path(workspace), class: "ws__block" do %>
    <div class="ws__content">
      <h2 class="ws__name"><%= workspace.name %></h2>
      <div class="ws__details">Last update on <%= workspace.updated_at.strftime("%d/%m/%Y") %>&nbsp; · &nbsp;<%= workspace.checklists.count %> checklists</div>
    </div>
  <% end %>
<% end %>

app/views/workspaces/index.html.erb
<main class="app__container">
  <header class="app__header">
    <h1>My workspaces</h1>
    <%= button_to "/workspaces", class: "button--primary" do %>
      <i class="bx bx-plus"></i>
      New workspace
    <% end %>
  </header>
  <div class="app__content">
    <%= render 'workspace_index', workspaces: @workspaces %>
  </div>
</main>

app/views/workspaces/show.html.erb
<main class="app__container">
  <header class="app__header">
    <div class="app__header--left">
      <h1><%= @workspace.name %></h1>
      <div class="header__options">
        <div data-controller="dropdown" class="relative">
          <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class="dropdown__button"><i class='bx bx-cog'></i></button>
          <div data-dropdown-target="menu" class="hidden dropdown__list">
            <%= render "shared/modal", route: "/workspaces/#{@workspace.id}" %>
            <%= link_to 'Delete', workspace_path(@workspace), data: {turbo_method: :delete, action: "dropdown#toggle" } %>
          </div>
        </div>
      </div>
    </div>
    <%= button_to workspace_checklists_path(@workspace), class: "button--primary" do %>
      <i class="bx bx-plus"></i>
      New checklist
    <% end %>
  </header>
  <div class="app__content">
    <% if @workspace.checklists.empty? %>
      <div>You don't have checklists in this workspace.</div>
    <% else %>
      <table class="ck__table">
        <tr class="ck__header">
          <th><div class="ck__header-col "><i class="bx bx-font-family"></i>Name</div></th>
          <th><div class="ck__header-col "><i class='bx bx-show'></i>Status</div></th>
          <th><div class="ck__header-col"><i class='bx bx-user'></i>Creator</div></th>
          <th><div class="ck__header-col"><i class='bx bx-check-double'></i>Completion</div></th>
          <th></th>
        </tr>
        <% @workspace.checklists.each do |checklist| %>
          <%= render 'checklists/checklist', checklist: checklist %>
        <% end %>
      </table>
    <% end %>
  </div>
</main>